version: '3'
services:
  company_templatez_frontend:
    image: 'company_templatez_frontend_${IMAGE_SUFFIX}'
    deploy:
      restart_policy:
        condition: always
    ports: 
      - '${EXTERNAL_FRONTEND_PORT}:3000'