version: '3'
services:
  company_template_frontend:
    networks: 
      company_template_frontend_development:
        aliases:
          - templatecifront
networks:
  company_template_frontend_development:
   external: true